version: "3.3"
services:

  db:
    image: postgres:12-alpine
    container_name: gp-ib
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ib
    ports:
      - 5437:5432