server:
  servlet:
    session:
      cookie:
        http-only: true
    context-path: "/"

spring:
  application:
    name: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CheckBinance
    username: postgres
    password: 123
    hikari:
      maxLifetime: 600000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false